const CARDS = [
  // =====================
  // セフィロト（11枚）
  // =====================
  {
    id: 'daat', name: "DA'AT", type: 'Sephirot',
    subs: ['Gate of the Abyss', "Readiness to face one's depths"],
    symbol: 'Ø', symbolColor: '#88ffcc',
    gradStops: [['#001a10','#002820'], ['#004a38','#00887a']],
    image: 'images/daat.png',
    keywords: '知識・深淵の扉・土星・ギメルのラクダが通過する扉・ビフロストへの接続点',
    upright: 'これまで積み重ねてきた努力・喜び・試練のすべてが一つの巨大な知恵として完全に融合しようとしている。天の直感と地上のリアルな経験がピタッと噛み合い、新しい次元へとシフトする人生の大きな特異点。あなたが歩いてきたすべての道が、深いところでは無駄なく、今ここに繋がっている。',
    reversed: '人生において最も核心に触れる大事なテーマと向き合っているがゆえの、神聖な足止め。「ここを超えられなければ終わりだ」という思い込みから、巨大で冷たい壁が見えている。しかしその「目詰まり」こそが、大反転のトリガーになる。',
  },
  {
    id: 'kether', name: 'KETHER', type: 'Sephirot',
    subs: ['The Crown', 'Pure Existence'],
    symbol: '✦', symbolColor: '#ffffff',
    gradStops: [['#0a0a0a','#1a1a2e'], ['#2a2a4a','#8888cc']],
    image: 'images/kether.png',
    keywords: '王冠・純粋な存在・無限の可能性・直感・根拠のない確信',
    upright: 'まだ何の色もついていない、純粋な「私は私である」という存在の全肯定。無限の可能性。あなたの「直感」や「根拠のない確信」に強烈な守護が入っている。外側で何が起ころうと深呼吸をしてその場にちゃんと立てる。',
    reversed: 'ありのままの自分では世界に存在してはいけないという恐怖。「完璧でなければ価値がない」という思い込みが100点か0点かの極端な世界を見せている。怖がっている自分を、抱きしめていよう。',
  },
  {
    id: 'chokmah', name: 'CHOKMAH', type: 'Sephirot',
    subs: ['Wisdom', 'Pure Inspiration'],
    symbol: '⊕', symbolColor: '#aaddff',
    gradStops: [['#001020','#002040'], ['#003366','#0066bb']],
    image: 'images/chokmah.png',
    keywords: '知恵・ロジックなしの直感・アイデアの爆発・衝動的なパッション',
    upright: 'ロジックなしの直感、アイデアの爆発。採算や他人の納得はいらない。あなたの「思いつき」や「衝動的なパッション」そのものに強烈な追い風が吹いている。',
    reversed: '自分の直感や感性を、過去にロジックや常識という檻に閉じ込められ、鎖に繋がれた危機感と支配への怒り。自らの感性を守るために、すべてを破壊するという防衛手段も厭わないかもしれない。そのくやしさと苦しさは必ず強いバネになる。',
  },
  {
    id: 'binah', name: 'BINAH', type: 'Sephirot',
    subs: ['Understanding', 'Form from Chaos'],
    symbol: '△', symbolColor: '#cc88ff',
    gradStops: [['#100020','#200040'], ['#3a0066','#7700cc']],
    image: 'images/binah.png',
    keywords: '理解・混沌に形を与えること・深い受容・母なる器・制限',
    upright: '深い理解と受容と厳しさ。形のないものに形を与え、守り育てるしなやかな知性。母なる器。感性がリアルな形を伴って世界に表現していくことを強くサポートしてくれる。',
    reversed: '自らの感性を信じられず、混沌の中で傷つき、見捨てられるという恐怖。「絶対にコントロールできるルール」という命綱が必要だった。その傷や恐怖が新しい居場所を創り出す最高の鍵に変わる。',
  },
  {
    id: 'chesed', name: 'CHESED', type: 'Sephirot',
    subs: ['Mercy', 'Unconditional Love'],
    symbol: '♃', symbolColor: '#ffdd88',
    gradStops: [['#1a1000','#332000'], ['#664400','#cc9900']],
    image: 'images/chesed.png',
    keywords: '慈悲・無条件の肯定と受容・大いなる慈悲・無限の拡大と豊かさ',
    upright: '大いなる慈悲、無限の拡大と豊かさそのもののエネルギー。「受け入れる力」や「育てるエネルギー」に強烈な追い風。守りに入るより流れに身を任せて循環させるとき。',
    reversed: '無条件で受け止められた経験が乏しく、「与え続けなければ見捨てられる」という深い飢餓感。尽くすことでしか価値がないと感じた苦しみが、本当の聖域を現実に創り出す最高の鍵になる。',
  },
  {
    id: 'geburah', name: 'GEBURAH', type: 'Sephirot',
    subs: ['Strength', 'Sacred Judgment'],
    symbol: '♂', symbolColor: '#ff6644',
    gradStops: [['#1a0000','#3a0000'], ['#770000','#cc2200']],
    image: 'images/geburah.png',
    keywords: '峻厳・適切な境界線の確立・本質ではないものを断ち切るNOの力・尊厳を守るための神聖な裁き',
    upright: '本質ではないものを断ち切るNOの力。尊厳を守るための神聖な裁き。「これ以上自分を安売りしなくていい」という強い守護。自分が守りたい領域をはっきりさせるチャンス。',
    reversed: '大切な領域を土足で踏みにじられたり、侵害されてきた無力感。自分の尊厳をどんな形でも守ろうとしたプライドこそ、自分自身や大切に思う人を防衛する盾となる。',
  },
  {
    id: 'tiphareth', name: 'TIPHARETH', type: 'Sephirot',
    subs: ['Beauty', 'The True Self'],
    symbol: '☀', symbolColor: '#ffcc00',
    gradStops: [['#1a1200','#332400'], ['#665500','#ccaa00']],
    image: 'images/tiphareth.png',
    keywords: '美・自己統合とありのままの輝き・中心軸（セルフ）とつながる太陽のような調和と美しさ',
    upright: '自分の中心軸（セルフ）とつながる太陽のような調和と美しさ。一番大切な価値観。「本当に在りたい生き方」や「等身大の自己表現」への強烈なスポットライト。',
    reversed: 'ありのままの未完成な自分では無視され、愛されないと感じた拒絶の痛み。自分には価値が無いと思う苦しみの記憶は、あなた自身だけの美しさを開花させるための最高の鍵になる。',
  },
  {
    id: 'netzach', name: 'NETZACH', type: 'Sephirot',
    subs: ['Victory', 'Wild Emotion'],
    symbol: '♀', symbolColor: '#88ff88',
    gradStops: [['#001a00','#003300'], ['#006600','#00aa44']],
    image: 'images/netzach.png',
    keywords: '勝利・野生の感情の解放・理由のない「大好き！」「心地いい！」というエモーショナルな熱量と芸術的感性',
    upright: '理由のない「大好き！」「心地いい！」というエモーショナルな熱量と芸術的感性。「正しさ」より「楽しさ・心地よさ」を選ぶとき。感覚を爆発させている姿そのものが最大の魅力になる。',
    reversed: '純粋な好きという気持ちや繊細な感覚を、過去に「くだらない」と踏みにじられた失望。言葉にできない美しさや違和感を丁寧に拾い上げる圧倒的な共鳴力は、閉ざされた心を一瞬で融かす最高の魔法になる。',
  },
  {
    id: 'hod', name: 'HOD', type: 'Sephirot',
    subs: ['Splendor', 'Language of Sensation'],
    symbol: '☿', symbolColor: '#ffaa44',
    gradStops: [['#1a0800','#331500'], ['#662a00','#cc5500']],
    image: 'images/hod.png',
    keywords: '栄光・感覚の言語化と客観的な知性・モヤモヤした感覚に名前を与える明晰さ',
    upright: 'モヤモヤした感覚に名前を与え、ロジックやシステムとして鮮やかに翻訳・整理する明晰さ。「伝える力」や「分析する知性」に強力なサポート。自己理解を含めた、他者や物事への理解を言葉を使って深めるのに最適な時。',
    reversed: 'リアルな感情をそのまま出したとき、理不尽に言いくるめられたり嘘つき呼ばわりされた悔しさ。物事の構造や嘘を見抜き、感覚を自らの言葉で翻訳する言語化能力は、自分の、そして誰かの閉ざされた部分を開ける最高のきっかけになる。',
  },
  {
    id: 'yesod', name: 'YESOD', type: 'Sephirot',
    subs: ['Foundation', 'The Dreaming Ground'],
    symbol: '☽', symbolColor: '#aaaaff',
    gradStops: [['#080018','#100030'], ['#220066','#4400cc']],
    image: 'images/yesod.png',
    keywords: '基盤・潜在意識の力と豊かなイマジネーション・夢や幻想・インスピレーションの活性化',
    upright: '夢や幻想、インスピレーションの活性化。現実化を足元から引き寄せる磁石（心の土台）。無意識のセンサーに強力な追い風。「本当にしたいこと」をじっくり味わうほど、心が満たされる時。',
    reversed: 'リアルな過去が過酷だったり、辛い記憶が多く、直視するのがくるしすぎるほどだった傷。内なる世界の中に命のシェルターを作ってここまで生き延びた、その内側の世界と知恵こそが人生の土台へと変化していく。',
  },
  {
    id: 'malkuth', name: 'MALKUTH', type: 'Sephirot',
    subs: ['Kingdom', 'Earth Embodied'],
    symbol: '⊕', symbolColor: '#bb8844',
    gradStops: [['#100800','#201500'], ['#443300','#886600']],
    image: 'images/malkuth.png',
    keywords: '王国・現実化と肉体を持った行動・アイデアやイメージを3次元の地球で結晶化させる力',
    upright: 'アイデアやイメージをこの3次元の地球で「目に見える形」として結晶化させる力。グラウンディングへの強烈な守護。具体的なタスクを淡々とこなすとき、地球そのものが足元をガシッと支えてくれる。',
    reversed: '目に見えない約束や愛を信じた結果、裏切られたり、足元をすくわれる恐怖を味わった傷。物事をリアルに着地させる具体化の力として、理想を地上に結晶化させる最高の鍵になる。',
  },

  // =====================
  // ヘブライ文字（22枚）
  // =====================
  {
    id: 'aleph', name: 'ALEPH', type: 'Hebrew',
    subs: ['The Fool (0)', 'Pure Possibility'],
    symbol: 'א', symbolColor: '#ffffff',
    gradStops: [['#050510','#0a0a20'], ['#1a1a40','#4444aa']],
    image: 'images/aleph.png',
    keywords: '愚者・無から飛び出す純粋な可能性・計算や損得を脇に置いた無垢さ・風元素',
    upright: '何も決まっていない、何の色もついていない。だからこそ、ここから何にだってなれる純粋な「存在の始まり」のエネルギー。「言葉にならない沈黙」の中にある、やってみたいけど現実的ではないと感じるようなことに、最も神聖な力が背中を押している。',
    reversed: '可能性を信じるのが怖くなるくらい、過去に自分の純粋な衝動を笑われたり踏みにじられた傷があったかもしれない。でも、あなたの魂の奥底にある「純粋な風（アレフ）」は1ミリも死んでいない。',
  },
  {
    id: 'beth', name: 'BETH', type: 'Hebrew',
    subs: ['The Magician (I)', 'Will into Form'],
    symbol: 'ב', symbolColor: '#ffee88',
    gradStops: [['#181000','#302000'], ['#604000','#cc8800']],
    image: 'images/beth.png',
    keywords: '魔術師・意志の力・上と下をつなぐ・道具の習熟・水星',
    upright: '「上にあるものは下にある」——天の意志を地上に実現させる意志と技術の統合。あなたが持っているすべての道具は、今この瞬間のために揃っている。',
    reversed: '自分の意志やもっている資質・能力を過去に「大した価値がない」と否定され続けた傷。誰かに笑われた記憶が、あなたの手を止めているのかもしれない。あなたの大切な道具たちは、仕舞われていただけで、今もちゃんと使える。',
  },
  {
    id: 'gimel', name: 'GIMEL', type: 'Hebrew',
    subs: ['The High Priestess (II)', 'Recall your North Star'],
    symbol: 'ג', symbolColor: '#ccaaff',
    gradStops: [['#0d0a1a','#1a1230'], ['#2d1f50','#5a3a9a']],
    image: 'images/gimel.png',
    keywords: 'ギメル（駱駝）・女教皇・ケテルとティファレトの道・月・内なる羅針盤',
    upright: '砂漠の横断——目印のない地平線でも、内なる羅針盤を信じること。論理では捉えきれない微細な感覚やインスピレーション、砂漠の厳しい気候を渡るための知恵と水分、共に、既にあなたの中にある。',
    reversed: '自分の望みではない光を追っている可能性があるかもしれない。他者の承認に依存する古いパターンから、自分自身の深い知恵を信頼する新しい在り方への移行を促している。',
  },
  {
    id: 'daleth', name: 'DALETH', type: 'Hebrew',
    subs: ['The Empress (III)', 'Where Grace Enters'],
    symbol: 'ד', symbolColor: '#ffbbdd',
    gradStops: [['#1a0010','#330020'], ['#660044','#cc0088']],
    image: 'images/daleth.png',
    keywords: 'ダレット（扉）・道・可能性への開口部・神の恩寵を構造として受け取る・外からはわからない扉・金星',
    upright: 'ひらめき（コクマー）と理解（ビナー）の間に立つ、見えない扉。扉であり道でもある——可能性へと通じる開口部。神の恩寵は、構造を持ってあなたの現実に降りてくる。今、その扉の前にいる。あとは、開けることを選ぶだけ。',
    reversed: '扉の存在に気づいていない、または見えているのに開けられない状態。過去に心を開いたとき傷ついた経験が、鍵を固く握らせているのかもしれない。でもこの扉は、外から壊されるものじゃない。あなたの内側からだけ、開く。',
  },
  {
    id: 'heh', name: 'HEH', type: 'Hebrew',
    subs: ['The Emperor (IV)', 'Structure and Authority'],
    symbol: 'ה', symbolColor: '#ff8844',
    gradStops: [['#1a0800','#331500'], ['#663300','#cc6600']],
    image: 'images/heh.png',
    keywords: '皇帝・構造と権威・秩序を作る力・牡羊座・火の意志',
    upright: '心の窓をそっと開けると、言葉にならないイメージや気力が、直接あなたの軸へと流れ込んでくる。それがあなたの王国を動かす力の源。外側の承認を待たなくていい——窓を開けることが、すでに統治の始まり。',
    reversed: '心の窓が閉まっている、または開け方を忘れてしまっているかもしれない。過去に窓を開けたとき、見えたものや流れ込んできたものが、痛かったり怖かったりした経験があったのかもしれない。でも、窓は家の中から開けるもの。今あなたがここにいるということは、安全な場所にいるということ。そして、開ける準備が整っているというお知らせかもしれない。',
  },
  {
    id: 'vav', name: 'VAV', type: 'Hebrew',
    subs: ['The Hierophant (V)', 'Bridge of Tradition'],
    symbol: 'ו', symbolColor: '#aabbff',
    gradStops: [['#080018','#100030'], ['#1a0055','#3300aa']],
    image: 'images/vav.png',
    keywords: '教皇・伝統と教えを橋渡しする・内なる師・牡牛座',
    upright: 'あなたの内側から湧いてくる知恵や感覚は、あなただけのものではない。それを社会や他者と結びつけるとき、釘がものとものを繋ぐように、見えない橋が生まれる。あなたの直感を、外の世界へ持ち出していい。',
    reversed: '自分の知恵や感覚を外に出したとき、否定されたり無視された経験があったのかもしれない。だから繋ぐことをやめて、内側に仕舞い込んでいるのかもしれない。でもその釘は、あなたと世界を繋ぐためにある。',
  },
  {
    id: 'zayin', name: 'ZAYIN', type: 'Hebrew',
    subs: ['The Lovers (VI)', 'The Choice'],
    symbol: 'ז', symbolColor: '#ffddaa',
    gradStops: [['#1a1000','#332000'], ['#664400','#bb8800']],
    image: 'images/zayin.png',
    keywords: '恋人・選択・二つの道の前に立つ・双子座・統合か分裂か',
    upright: '二つの道の前に立っている。これは単なる恋愛の選択ではなく、「どの自分として生きるか」という魂の選択。あなたの心が本当に動く方を、信頼して。',
    reversed: '選択することへの深い恐怖。「選んだら何かを失う」「どちらも正しい気がして動けない」——その分裂の痛みそのものが、あなたが何を大切にしているかを教えてくれる。',
  },
  {
    id: 'cheth', name: 'CHETH', type: 'Hebrew',
    subs: ['The Chariot (VII)', 'Directed Will'],
    symbol: 'ח', symbolColor: '#88ccff',
    gradStops: [['#001018','#002030'], ['#004466','#0088bb']],
    image: 'images/cheth.png',
    keywords: '戦車・相反する力を御する意志・前進・蟹座',
    upright: 'あなたの中に燃えている熱意や情熱——その炎を守るのは、あなた自身。何を自分の聖域に入れて、何を入れないかを決めることが、炎を消さないための柵になる。境界を引くことは、冷たさじゃない。炎への愛情だ。',
    reversed: '炎を守るための柵を作れなかった、または作り方がわからなかったのかもしれない。誰かに踏み込まれて、熱意ごと消されてしまった経験があったのかもしれない。その炎はまだ、あなたの中にある。',
  },
  {
    id: 'tet', name: 'TET', type: 'Hebrew',
    subs: ['Strength (VIII)', 'The Gentle Taming'],
    symbol: 'ט', symbolColor: '#ffaa66',
    gradStops: [['#180800','#301500'], ['#602800','#bb5500']],
    image: 'images/tet.png',
    keywords: '力・優しさで野性を御する・内なる獅子・乙女座または獅子座',
    upright: '自分の中にある強烈な感情や衝動——その熱を、力でねじ伏せようとしなくていい。まず静かに観察する。その動きを理解したとき、蛇がしなやかに動くように、そのエネルギーは知恵に変わる。',
    reversed: '自分の中の強い熱や衝動を「あってはならないもの」として封じ込めてきたのかもしれない。でもその熱は、悪いものじゃなくて強いものだっただけ。焦らなくても、その扱いを覚えられるのはあなた以外にいない。',
  },
  {
    id: 'yod', name: 'YOD', type: 'Hebrew',
    subs: ['The Hermit (IX)', 'The Inner Light'],
    symbol: 'י', symbolColor: '#ffffaa',
    gradStops: [['#101000','#202000'], ['#404400','#888800']],
    image: 'images/yod.png',
    keywords: '隠者・内なる光を灯して道を照らす・孤独な探求・乙女座',
    upright: '孤独の中で内なる光を灯しながら、魂の道を照らす隠者のとき。外の喧騒から離れ、自分の内側に深く降りていくことへの強烈な守護。その孤独は孤立ではなく、自分と自分、自分と世界の深い対話。',
    reversed: '孤立が孤独になってしまっているとき。「誰にもわかってもらえない」という深い孤独感。しかし、その孤独の深さほど、あなたの内なる光は明るい。灯台は、自分のために光らなくていい。',
  },
  {
    id: 'kaf', name: 'KAF', type: 'Hebrew',
    subs: ['Wheel of Fortune (X)', 'The Great Turning'],
    symbol: 'כ', symbolColor: '#cc88ff',
    gradStops: [['#100018','#200030'], ['#3a0066','#7700cc']],
    image: 'images/kaf.png',
    keywords: '運命の輪・大いなる循環・転機・木星・宇宙の流れに乗る',
    upright: '手のひらを開いているとき、豊かさと喜びは同じものになる。受け取ることが喜びで、喜ぶことが豊かさ——その循環が、今あなたの手の中で動き始めている。',
    reversed: '喜んでいいのか、豊かさを受け取っていいのか、どこかで許可が出せないのかもしれない。過去に手を開いたとき、奪われたり、喜びを壊された経験があったから。でも、その手のひらはちゃんと与えられる。',
  },
  {
    id: 'lamed', name: 'LAMED', type: 'Hebrew',
    subs: ['Justice (XI)', 'The Honest Mirror'],
    symbol: 'ל', symbolColor: '#88ffdd',
    gradStops: [['#001810','#003020'], ['#006644','#00bb88']],
    image: 'images/lamed.png',
    keywords: '正義・因果の法則・公正な目でみること・天秤座',
    upright: '公正な目で自分と状況を見つめるとき。感情に流されず、しかし冷酷にもならず——バランスの取れた判断が求められている。あなたの内なる正義感は、信頼できる。',
    reversed: '自分を裁きすぎている、または不公平な裁きを受けてきた傷。「正しくなければ愛されない」という信念の重さ。しかし正義は、あなたを罰するためにあるのではない。あなたの大事なものの重みを知るためにある。',
  },
  {
    id: 'mem', name: 'MEM', type: 'Hebrew',
    subs: ['The Hanged Man (XII)', 'Sacred Surrender'],
    symbol: 'מ', symbolColor: '#88aaff',
    gradStops: [['#000818','#001030'], ['#002266','#0044cc']],
    image: 'images/mem.png',
    keywords: '吊るされた男・聖なる降伏・視点の180度反転・水元素',
    upright: '熱意や激しい感情は、水を通ることで静かに深くなる。今、あなたの強い熱意を深みと落ち着きのある言葉や知恵に変えていく流れが強くなっている。',
    reversed: '熱いまま言葉にしようとして、うまく伝わらなかった経験があったのかもしれない。または逆に、冷やされすぎて言葉が出てこなくなっているのかもしれない。その経験こそが、言語化や知恵にする力となっていく。',
  },
  {
    id: 'nun', name: 'NUN', type: 'Hebrew',
    subs: ['Death (XIII)', 'Transformation'],
    symbol: 'נ', symbolColor: '#446688',
    gradStops: [['#050510','#0a0a18'], ['#101030','#2a2a66']],
    image: 'images/nun.png',
    keywords: '死・変容・終わりと始まり・蠍座・古い皮を脱ぐ',
    upright: '結果がどうなるかより、今この動きそのものが心地いい。その純粋な動機から生まれるエネルギーは、止まる必要がない。心地よく好きなだけ泳げるとき。',
    reversed: '動き続けることが止められなくなっているかもしれない。止まると何かを失う気がして、過度に動き続けてしまう。本当は疲れている自分に気づくとき。',
  },
  {
    id: 'samekh', name: 'SAMEKH', type: 'Hebrew',
    subs: ['Temperance (XIV)', 'The Alchemist'],
    symbol: 'ס', symbolColor: '#aaffcc',
    gradStops: [['#001510','#002820'], ['#005540','#00aa80']],
    image: 'images/samekh.png',
    keywords: '節制・錬金術・対立する力の融合・射手座',
    upright: '表層の自分と潜在意識が、炎の輪のように途切れず循環している。内側と外側にズレがない状態——言っていることとやっていること、見せている自分と本当の自分が、同じ場所にいる。',
    reversed: '表向きの自分と内側の自分にズレが生じているかもしれない。その摩擦が疲れや違和感として出てきているのかもしれない。本当はどう在りたいか、内側から問われている。',
  },
  {
    id: 'ayin', name: 'AYIN', type: 'Hebrew',
    subs: ['The Devil (XV)', 'Shadow Chains'],
    symbol: 'ע', symbolColor: '#886644',
    gradStops: [['#100800','#201000'], ['#402000','#884400']],
    image: 'images/ayin.png',
    keywords: '悪魔・シャドウの鎖・物質への執着・山羊座・見えない縛り',
    upright: '今のあなたを縛っている鎖を直視するとき。その鎖は外から与えられたように見えるが、実はあなた自身が握っている。シャドウの正体を見ることで、自由が始まる。',
    reversed: 'その鎖を外す恐怖——「自由になったら何が起きるかわからない」という深い不安。その縛りは、かつてあなたを守るために必要だったもの。その歴史への敬意と共に、少しずつ手を開いていい。',
  },
  {
    id: 'pe', name: 'PE', type: 'Hebrew',
    subs: ['The Tower (XVI)', 'Sacred Destruction'],
    symbol: 'פ', symbolColor: '#ff4422',
    gradStops: [['#1a0000','#380000'], ['#770000','#dd2200']],
    image: 'images/pe.png',
    keywords: '塔・聖なる破壊・嘘の構造物の崩壊・火星',
    upright: '勇気のいることを言葉にして外に出したとき、何かが解放される。その瞬間、積み上げてきたものが壊れるかもしれない。でもその口から出た言葉が、本当の自分を世界に繋ぐ。',
    reversed: '言いたいことが喉の奥で止まっているかもしれない。壊れることへの恐怖が、口を閉じさせている。でもその言葉は、あなたに表現してもらうのをずっと待っている。',
  },
  {
    id: 'tzadi', name: 'TZADI', type: 'Hebrew',
    subs: ['The Star (XVII)', 'Hope Returns'],
    symbol: 'צ', symbolColor: '#aaccff',
    gradStops: [['#000818','#001030'], ['#001866','#0033cc']],
    image: 'images/tzadi.png',
    keywords: '星・希望の光・嵐のあとの静けさ・水瓶座',
    upright: '好きなこと、好きなものは、永遠に失われない。ただ潜在意識の深いところで眠っているだけ。その暗闇に釣り針を垂らすとき、光はちゃんと引き上げられてくる。',
    reversed: '好きだったものを感じられなくなっているかもしれない。失ってしまったと思っているかもしれない。でもそれは消えていない。ただ、深いところで眠っているだけ。',
  },
  {
    id: 'qof', name: 'QOF', type: 'Hebrew',
    subs: ['The Moon (XVIII)', 'The Depths Revealed'],
    symbol: 'ק', symbolColor: '#8888cc',
    gradStops: [['#080010','#100020'], ['#200044','#440088']],
    image: 'images/qof.png',
    keywords: '月・無意識の深み・幻想と直感の境界・魚座',
    upright: '無意識の深みから何かが浮かび上がってきている。それは一見、不安やモヤや言葉にならない違和感かもしれない。でもそれは本能の声。自分では見えない後頭部から溢れ出る、とても大事なメッセージ。',
    reversed: '浮かび上がってくるものを「気のせいだ」「よくないものだ」と押し戻しているかもしれない。でもその感覚は、あなたを守るために出てきている。',
  },
  {
    id: 'resh', name: 'RESH', type: 'Hebrew',
    subs: ['The Sun (XIX)', 'Radiant Joy'],
    symbol: 'ר', symbolColor: '#ffdd00',
    gradStops: [['#1a1200','#332400'], ['#665500','#ccaa00']],
    image: 'images/resh.png',
    keywords: '太陽・輝き・子どものような喜び・成功と祝福',
    upright: '子どものような無垢な喜び、太陽の下で輝くとき。あなたの存在そのものが光。成功、健康、喜び——それらはすでにあなたの中にある。ただそれを、世界に向けて開いていい。',
    reversed: '喜ぶことへの恐怖、または輝くことへの罪悪感。「自分だけ幸せになっていいのか」という思い込み。その曇りを通しても、あなたの太陽は消えていない。',
  },
  {
    id: 'shin', name: 'SHIN', type: 'Hebrew',
    subs: ['Judgement (XX)', 'The Great Resurrection'],
    symbol: 'שׁ', symbolColor: '#ff6600',
    gradStops: [['#1a0400','#380800'], ['#771100','#cc3300']],
    image: 'images/shin.png',
    keywords: '審判・聖なる火が過去を全肯定へ昇華する・魂の復活・火元素',
    upright: '歯が食べ物を砕いて栄養に変えるように、炎が木を燃やして光と熱に変えるように——今あなたの中で、何かが元の形を失いながら、全く新しいものに変容している。それは喪失ではなく、変換。',
    reversed: '砕かれることへの恐怖から、噛めないでいるのかもしれない。でもシンの炎は、あなたを消すためにあるんじゃない。新しい形に変えるために、ここにある。',
  },
  {
    id: 'tav', name: 'TAV', type: 'Hebrew',
    subs: ['The World (XXI)', 'Completion'],
    symbol: 'ת', symbolColor: '#aaffaa',
    gradStops: [['#001800','#003000'], ['#006600','#00cc44']],
    image: 'images/tav.png',
    keywords: '世界・完成・一つのサイクルの終わりと新たな始まり・土星',
    upright: '一つの大きなサイクルが完成する瞬間。宇宙の舞踊の中で、あなたはすべての要素を統合した。この完成は終わりではなく、次の大きな螺旋の出発点。今、全力で祝っていい。',
    reversed: '完成を認められない、または次のステップへの恐怖。「もっと完璧にならないと」という思い込みで、すでに成し遂げたものを見えなくしている。あなたはすでに、十分に遠くまで来た。',
  },

  // =====================
  // 九つの世界 + ヴァルハラ + ビフロスト（11枚）
  // =====================
  {
    id: 'asgard', name: 'ASGARD', type: 'World',
    subs: ['Realm of the Aesir', 'Divine Order'],
    symbol: '⚡', symbolColor: '#ffdd44',
    gradStops: [['#1a1400','#332800'], ['#665500','#ccaa00']],
    image: 'images/asgard.png',
    keywords: 'アースガルズ・神々の領域・秩序と権威・オーディンの館・天上界',
    upright: '神々の秩序と権威のエネルギーが働いている。高い視点から物事を見渡す力、大局を把握する知性。あなたは今、自分の人生の主権者として立つべきとき。',
    reversed: '神の権威を笠に着た支配、または権威への過剰な服従。「高みから見下ろされる」感覚の傷。しかし本物の権威は、制圧ではなく守護から来る。',
  },
  {
    id: 'midgard', name: 'MIDGARD', type: 'World',
    subs: ['The Human Realm', 'Here and Now'],
    symbol: '⊕', symbolColor: '#88bb44',
    gradStops: [['#080c00','#101800'], ['#243300','#4a6600']],
    image: 'images/midgard.png',
    keywords: 'ミドガルズ・人間の世界・今ここにある現実・日常の中の神聖さ',
    upright: '今ここにある現実、日常の中の神聖さ。あなたの足元にある地面こそが、すべての旅の出発点。この日常の中に、神話が息づいている。',
    reversed: '日常の重さに押しつぶされているとき、または現実から逃げたいとき。その「ただの毎日」の中に、見過ごしてきた宝が隠れている。',
  },
  {
    id: 'jotunheim', name: 'JOTUNHEIM', type: 'World',
    subs: ['Realm of Giants', 'Ancient Forces'],
    symbol: '⛰', symbolColor: '#8899aa',
    gradStops: [['#080a10','#101520'], ['#202840','#404f77']],
    image: 'images/jotunheim.png',
    keywords: 'ヨトゥンヘイム・巨人族の世界・古代の力・コントロールできない自然の猛威',
    upright: 'コントロールできない古代の力、自然の猛威のエネルギーが動いている。それに抗うのではなく、その巨大さを尊重して流れる方法を見つけるとき。',
    reversed: '巨大な力への恐怖、または自分の中の手に負えない感情への恐れ。しかし、ヨトゥンの力はあなたを壊すためにあるのではない。',
  },
  {
    id: 'vanaheim', name: 'VANAHEIM', type: 'World',
    subs: ['Realm of the Vanir', 'Nature Magic'],
    symbol: '❀', symbolColor: '#88ff88',
    gradStops: [['#001800','#003000'], ['#006600','#00cc44']],
    image: 'images/vanaheim.png',
    keywords: 'ヴァナヘイム・ヴァン神族の世界・自然の魔法・豊穣・フレイとフレイヤ',
    upright: '豊穣と自然の魔法。フレイヤの愛の力、フレイの豊穣のエネルギーが流れている。感覚的な喜び、繁栄、性的な創造力への強烈な守護。',
    reversed: '自然の流れや感覚的な喜びから切り離されているとき。「欲しいと思ってはいけない」という禁止令。あなたの欲望は、生命そのものの声。',
  },
  {
    id: 'alfheim', name: 'ALFHEIM', type: 'World',
    subs: ['Realm of Light Elves', 'Inspiration'],
    symbol: '✧', symbolColor: '#ddeeff',
    gradStops: [['#080c18','#101830'], ['#202848','#3a4888']],
    image: 'images/alfheim.png',
    keywords: 'アルフヘイム・光のエルフの世界・インスピレーション・創造的な火花',
    upright: '光のエルフが運ぶインスピレーションと創造の火花。あなたのアイデアや感性は、今、高次の領域から直接届いている。その「ひらめき」を信頼して形にするとき。',
    reversed: 'インスピレーションが枯渇しているとき、または創造性を否定されてきた傷。光のエルフは気まぐれではない——あなたが疲れているとき、彼らは静かに待っている。',
  },
  {
    id: 'svartalfheim', name: 'SVARTALFHEIM', type: 'World',
    subs: ['Realm of Dark Elves', 'Hidden Craft'],
    symbol: '⚙', symbolColor: '#666688',
    gradStops: [['#080808','#101010'], ['#202030','#3a3a55']],
    image: 'images/svartalfheim.png',
    keywords: 'スヴァルタルヘイム・闇のエルフの世界・隠れた技術・深い職人芸',
    upright: '見えない場所での職人的な技術と努力。誰も見ていなくても、あなたは確かな技を磨いている。その地道な積み重ねが、やがて世界を変える道具を生み出す。',
    reversed: '隠れて作業することの孤独感、または評価されない苦しさ。しかし、ドワーフの最高の作品は、地下で生まれた。その暗闇での制作が本物の力になる。',
  },
  {
    id: 'niflheim', name: 'NIFLHEIM', type: 'World',
    subs: ['Realm of Mist', 'The Primordial Cold'],
    symbol: '❄', symbolColor: '#aaddff',
    gradStops: [['#000810','#001020'], ['#002040','#004488']],
    image: 'images/niflheim.png',
    keywords: 'ニフルヘイム・霧の世界・原初の冷たさ・始原の氷・感覚の麻痺',
    upright: '霧の中に包まれているとき。何も見えない、何も感じられない——その無感覚は、魂が嵐の中で自分を守るための凍結。今は動かなくていい。霧はやがて晴れる。',
    reversed: 'その凍結が長くなりすぎているとき。感情が完全に麻痺し、生きている感覚が薄くなっているとき。ニフルヘイムの氷は始まりの物質——いつか必ず、火との出会いで融ける。',
  },
  {
    id: 'muspelheim', name: 'MUSPELHEIM', type: 'World',
    subs: ['Realm of Fire', 'Primordial Destruction'],
    symbol: '🔥', symbolColor: '#ff6600',
    gradStops: [['#1a0400','#380800'], ['#771100','#cc3300']],
    image: 'images/muspelheim.png',
    keywords: 'ムスペルスヘイム・炎の世界・原初の火・スルトの炎・破壊的創造',
    upright: '原初の炎が燃え盛るとき。古いものを焼き尽くし、灰の中から新しいものが生まれる。その破壊は浄化。あなたの中の消えかけていた炎が、再び燃え上がる。',
    reversed: '怒りや激情のコントロールが効かなくなっているとき、または逆に炎が完全に消えてしまったとき。スルトの炎は終末のためにある——しかし今、その炎はあなたの内側で新しいものを創るためにある。',
  },
  {
    id: 'helheim', name: 'HELHEIM', type: 'World',
    subs: ['Total acceptance,', 'numbness'],
    symbol: '⬡', symbolColor: '#7fddff',
    gradStops: [['#00101a','#002233'], ['#004466','#0088bb']],
    image: 'images/helheim.png',
    keywords: 'ヘルの領域・全受容・すべてが最終的に安らぐ場所・静水の下',
    upright: '静水の下——死ではなく、変容の前の静止。ラディカルな受け入れ。ヘルは冷たい女神ではなく、すべてを平等に受け入れる慈悲の場所。今のあなたに必要なのは、全受容という深い休息。',
    reversed: '平和と見せかけた麻痺、降伏に偽装した回避。「もう何も感じたくない」という麻痺の中にいるとき。その無感覚は、かつてあなたが生き延びるために選んだ戦略だった。',
  },
  {
    id: 'valhalla', name: 'VALHALLA', type: 'World',
    subs: ['Hall of the Fallen', 'Honored Wounds'],
    symbol: '⚔', symbolColor: '#ffcc66',
    gradStops: [['#180c00','#302000'], ['#604000','#cc8000']],
    image: 'images/valhalla.png',
    keywords: 'ヴァルハラ・英雄たちの館・名誉ある戦いの記憶・傷を誇りへ',
    upright: '戦って傷ついた者だけが入れる館。あなたの傷は、弱さの証拠ではなく、戦った証拠。その傷を持つあなたを、ヴァルキューレが迎えに来ている。誇りを持って立て。',
    reversed: '傷つくことへの恐怖、または傷を恥じ続けているとき。「こんな自分では価値がない」という思い込み。あなたの傷に刻まれた歴史こそが、最も美しい勲章。',
  },
  {
    id: 'bifrost', name: 'BIFROST', type: 'World',
    subs: ['The Rainbow Bridge', 'Between Worlds'],
    symbol: '🌈', symbolColor: '#ffaaff',
    gradStops: [['#100018','#200030'], ['#3a0055','#880099']],
    image: 'images/bifrost.png',
    keywords: 'ビフロスト・虹の橋・世界と世界をつなぐ・見えない力が降りてくる・ダアトとの接続',
    upright: '見えない世界と見える世界をつなぐ虹の橋が現れているとき。神聖なものがあなたのもとへ降りてこようとしている。扉を開ける意志を持った魂だけが、この橋の上に立てる。',
    reversed: '橋が渡れないとき——見えない世界への不信、または「自分にはそんな価値がない」という思い込み。しかし、虹は両岸から見える。あなたの側からも、その橋は光っている。',
  },

  // =====================
  // ルーン文字（24枚）
  // =====================
  {
    id: 'fehu', name: 'FEHU', type: 'Rune',
    subs: ['Cattle · Wealth', 'Mobile Fortune'],
    symbol: 'ᚠ', symbolColor: '#ffcc44',
    gradStops: [['#1a1000','#332000'], ['#665500','#bbaa00']],
    image: 'images/fehu.png',
    keywords: '家畜・富・循環する豊かさ・エネルギーの流れ・フレイのアエット',
    upright: '富と豊かさのエネルギーが動いている。貯め込むのではなく、流し続けることで豊かさは増す。あなたの才能、時間、愛——それらを循環させるとき。',
    reversed: '豊かさを受け取ることへの恐怖、または喪失への執着。「持っていなければ価値がない」という思い込み。真の富は、流れの中にある。',
  },
  {
    id: 'uruz', name: 'URUZ', type: 'Rune',
    subs: ['Aurochs · Wild Strength', 'Primal Force'],
    symbol: 'ᚢ', symbolColor: '#cc8844',
    gradStops: [['#100800','#201500'], ['#4a2a00','#996600']],
    image: 'images/uruz.png',
    keywords: '原牛・野生の力・原始的な生命力・通過儀礼・フレイのアエット',
    upright: '野生の原牛のような生命力。コントロールを手放し、原始的な力に身を任せるとき。あなたの中に眠る野性の強さが目覚めようとしている。',
    reversed: '生命力の消耗、または力への恐怖。その疲れは本物——しかしウルズの牛は、倒れても立ち上がる。あなたの根底にある生命力は、まだ燃えている。',
  },
  {
    id: 'thurisaz', name: 'THURISAZ', type: 'Rune',
    subs: ['Thorn · Giant', 'Protective Force'],
    symbol: 'ᚦ', symbolColor: '#ff6644',
    gradStops: [['#1a0400','#380800'], ['#661100','#cc2200']],
    image: 'images/thurisaz.png',
    keywords: '棘・巨人・トール神・保護の力・境界線・フレイのアエット',
    upright: '棘は攻撃のためではなく、守護のためにある。今、あなたには明確な境界線を引く力が与えられている。その「NO」は、あなた自身と大切なものを守る神聖な棘。',
    reversed: '境界線を引けずに傷ついているとき、または棘が暴走しているとき。その攻撃性の奥には、深く傷つけられた心がある。守るべきものは、まず自分自身。',
  },
  {
    id: 'ansuz', name: 'ANSUZ', type: 'Rune',
    subs: ['God · Message', 'Divine Communication'],
    symbol: 'ᚨ', symbolColor: '#aabbff',
    gradStops: [['#080818','#101030'], ['#202260','#4044cc']],
    image: 'images/ansuz.png',
    keywords: 'オーディン・神の言葉・メッセージ・コミュニケーション・インスピレーション・フレイのアエット',
    upright: 'オーディンからの直接のメッセージが届いているとき。言葉、詩、インスピレーション——あなたを通して語ろうとしている何かがある。その声を聞いて、言葉にする。',
    reversed: 'コミュニケーションの断絶、または言葉が本当の意味を失っているとき。言葉が届かない孤独感。しかし、真の言葉は沈黙の中からも伝わる。',
  },
  {
    id: 'raidho', name: 'RAIDHO', type: 'Rune',
    subs: ['Journey · Rhythm', 'The Right Path'],
    symbol: 'ᚱ', symbolColor: '#88aadd',
    gradStops: [['#080c18','#101830'], ['#1c2a55','#3a55bb']],
    image: 'images/raidho.png',
    keywords: '旅・リズム・正しい道・移動・宇宙のリズムに乗る・フレイのアエット',
    upright: '旅のルーン——今のあなたは正しい道を歩んでいる。目的地よりも、その旅のリズムに意識を向けるとき。宇宙の大きなリズムに同調して動くとき、最短距離が見えてくる。',
    reversed: '道を見失っているとき、または間違った方向へ進んでいる感覚。その迷いは、本当の方向を知っているから生まれる。立ち止まって、足元の感覚を確かめて。',
  },
  {
    id: 'kenaz', name: 'KENAZ', type: 'Rune',
    subs: ['Torch · Knowledge', 'Creative Fire'],
    symbol: 'ᚲ', symbolColor: '#ffaa44',
    gradStops: [['#1a0800','#331500'], ['#663000','#cc6600']],
    image: 'images/kenaz.png',
    keywords: '松明・知識・創造の火・技術・内なる光・フレイのアエット',
    upright: '内なる光、創造の炎が燃えているとき。技術、知識、制作——あなたの手の中に光がある。その光を持って、暗闇の中を照らす。知ることそのものが、力になる。',
    reversed: '創造の火が消えかけているとき。インスピレーションの枯渇、または自分の光を信じられないとき。松明は消えても、火種は残っている。もう一度、息を吹きかけてみて。',
  },
  {
    id: 'gebo', name: 'GEBO', type: 'Rune',
    subs: ['Gift · Exchange', 'Sacred Balance'],
    symbol: 'ᚷ', symbolColor: '#ffddaa',
    gradStops: [['#181000','#302000'], ['#604400','#bb8800']],
    image: 'images/gebo.png',
    keywords: '贈り物・交換・対等な関係・神聖なバランス・フレイのアエット',
    upright: '真の贈り物は対等な交換から生まれる。一方的な与えでも取りでもなく、魂と魂が等しく交わるとき。あなたの存在そのものが、誰かへの最大の贈り物。',
    reversed: '与えすぎて枯渇しているとき、または受け取ることを拒否しているとき。ギャバは言う——受け取ることもまた、与えること、と。',
  },
  {
    id: 'wunjo', name: 'WUNJO', type: 'Rune',
    subs: ['Joy · Clan', 'True Belonging'],
    symbol: 'ᚹ', symbolColor: '#ffff88',
    gradStops: [['#181800','#303000'], ['#666600','#cccc00']],
    image: 'images/wunjo.png',
    keywords: '喜び・仲間・真の帰属感・調和・フレイのアエット',
    upright: '真の喜び、仲間との調和のとき。あなたは今、本当の意味で「居場所」にいる。または、その場所への道が開かれている。この喜びを、遠慮なく受け取っていい。',
    reversed: '喜びを感じることへの罪悪感、または仲間外れの痛み。「自分だけ幸せになっていいのか」という思い込み。喜びはあなたの権利——生まれてきたその瞬間から。',
  },
  {
    id: 'hagalaz', name: 'HAGALAZ', type: 'Rune',
    subs: ['Hail · Disruption', 'Necessary Chaos'],
    symbol: 'ᚺ', symbolColor: '#aaccff',
    gradStops: [['#080c18','#101830'], ['#1a2a50','#3a5599']],
    image: 'images/hagalaz.png',
    keywords: '雹・混乱・必要な破壊・コントロールできない変化・ハガルのアエット',
    upright: '雹が降り注ぐとき——コントロールできない外からの破壊。しかしハガラズの雹は、やがて地に溶けて水になる。この混乱は、新しい成長のための「強制的なリセット」。',
    reversed: '混乱への恐怖から、すべてをコントロールしようとしているとき。または、嵐の中で完全に立ちすくんでいるとき。嵐には必ず終わりがある——あなたは今、その中を通過している。',
  },
  {
    id: 'nauthiz', name: 'NAUTHIZ', type: 'Rune',
    subs: ['Need · Constraint', 'Fire from Friction'],
    symbol: 'ᚾ', symbolColor: '#cc8866',
    gradStops: [['#180800','#301500'], ['#5a2800','#aa5500']],
    image: 'images/nauthiz.png',
    keywords: '必要・制約・摩擦・必要は発明の母・制限から創造が生まれる・ハガルのアエット',
    upright: '摩擦木から生まれた火。制限の中から創造が生まれる。今のあなたの制約は、あなたの内なる火を引き出すための摩擦。「内なる火」へのサポート。',
    reversed: '制約への絶望、または制限の中での自己消耗。限界を感じて絶望するとき、その苦しさはあなたが本当に限界まで頑張ってきた証拠。ナウティズの火は、摩擦がなければ生まれない。',
  },
  {
    id: 'isa', name: 'ISA', type: 'Rune',
    subs: ['Ice · Stillness', 'Inward Journey'],
    symbol: 'ᛁ', symbolColor: '#ddeeff',
    gradStops: [['#080c10','#101820'], ['#1a2840','#304a77']],
    image: 'images/isa.png',
    keywords: '氷・静止・収縮・自我の固化・内省のとき・ハガルのアエット',
    upright: '完全な静止。氷のように動きが止まった状態。今は動かないことが正解。外側への拡張が止まり、内側に向かう。「静止と内省」への守護。',
    reversed: '凍結への恐怖、または自我の過剰な硬化。動けない自分を責めたり、逆に凍りついたまま溶けられないとき——氷は必ず溶ける。静止の中で、次のための力を蓄えている。',
  },
  {
    id: 'jera', name: 'JERA', type: 'Rune',
    subs: ['Year · Harvest', 'Patience Rewarded'],
    symbol: 'ᛃ', symbolColor: '#aabb44',
    gradStops: [['#0a1000','#141e00'], ['#2a3c00','#507700']],
    image: 'images/jera.png',
    keywords: '年・収穫・サイクル・蒔いた種が実る・自然なリズム・ハガルのアエット',
    upright: '一年の循環、収穫の時。蒔いた種が実る——因果の法則。急ぐことのできない成熟のプロセス。あなたがやってきたことは、ちゃんと報われる時期に来ている。',
    reversed: '収穫への焦りと不信、または実りを受け取れないとき。あなたが確かに蒔いた種は、確かに育っている。ただ、自然の時間は人間の焦りより遅い。',
  },
  {
    id: 'eihwaz', name: 'EIHWAZ', type: 'Rune',
    subs: ['Yew Tree · Death & Rebirth', 'World Tree'],
    symbol: 'ᛇ', symbolColor: '#226644',
    gradStops: [['#040c08','#081810'], ['#103025','#205545']],
    image: 'images/eihwaz.png',
    keywords: 'イチイの木・ユグドラシル・生と死の境界・変容・通過儀礼・ハガルのアエット',
    upright: 'ユグドラシル（世界樹）との関連。生と死の境界に立つルーン——死を知ることが真の力を生む。今のあなたは深い変化の真っ只中にいる。その変化は本物。',
    reversed: '変容への抵抗、または境界の混乱。変わることが怖い、自分が誰なのかわからなくなるのは、本当に深い変容が起きているサイン。根は死の世界まで届きながら、枝は天を突き刺す。',
  },
  {
    id: 'perthro', name: 'PERTHRO', type: 'Rune',
    subs: ['Fate Vessel · Mystery', 'The Hidden Lot'],
    symbol: 'ᛈ', symbolColor: '#aa88cc',
    gradStops: [['#0c0818','#181030'], ['#2c2050','#5540aa']],
    image: 'images/perthro.png',
    keywords: '運命・秘密・サイコロ壺・ノルン・隠された知識・ハガルのアエット',
    upright: '最も謎めいたルーン。サイコロ壺、または運命の容器。ノルンが紡ぐ糸の全体像は、いずれ見えてくる。今はわからなくていい。その謎を、楽しむ余白を作ってみよう。',
    reversed: 'コントロールへの執着、または運命への諦め。わからないことへの恐怖は、過去に「わからないまま」に傷つけられた記憶があるから。運命は容器の中で静かに待っている。',
  },
  {
    id: 'algiz', name: 'ALGIZ', type: 'Rune',
    subs: ['Elk · Divine Connection', 'Sacred Protection'],
    symbol: 'ᛉ', symbolColor: '#ccffcc',
    gradStops: [['#001808','#003010'], ['#006630','#00cc66']],
    image: 'images/algiz.png',
    keywords: 'ヘラジカ・防護・神との繋がり・目覚め・高次の意識へのアクセス・ハガルのアエット',
    upright: 'ヘラジカの角、または人が両手を天に向けて立つ姿。神との繋がりと防護のルーン。あなたの内なる聖域は、今、完璧に守られている。',
    reversed: '防護の過剰発動、または神聖なものへの接続の喪失。両手を天に向けるその姿勢は、今のあなたにも宿っている。内なる聖域は消えていない。',
  },
  {
    id: 'sowilo', name: 'SOWILO', type: 'Rune',
    subs: ['From Fragmentation', 'to Integration'],
    symbol: 'ᛊ', symbolColor: '#ffd966',
    gradStops: [['#1a0e00','#3d2200'], ['#8a5c00','#c9a84c']],
    image: 'images/sowilo.png',
    keywords: '太陽・勝利・全体性・分裂した自己を光で統合する・ハガルのアエット',
    upright: '勝利のルーン、稲妻の閃光。分裂した自己を一つに戻す力——影と光が統合された全体性。あなたが自分の全体（光も影も）を受け入れたとき、その輝きは誰にも消せないものになる。',
    reversed: '勝利への恐れ、または光の中に立つことへの怖さ。うまくいくこと、輝くことが怖いなら、過去に光の中に立って傷ついた経験があるのかもしれない。その勝利を、あなた自身が一番先に祝ってあげよう。',
  },
  {
    id: 'tiwaz', name: 'TIWAZ', type: 'Rune',
    subs: ['Tyr · Justice', 'Sacred Sacrifice'],
    symbol: 'ᛏ', symbolColor: '#88aaff',
    gradStops: [['#080818','#101030'], ['#1c2060','#3840cc']],
    image: 'images/tiwaz.png',
    keywords: 'テュール神・正義・自己犠牲・大義のための個人的損失・テュールのアエット',
    upright: 'テュールは狼フェンリルを縛るために自らの右手を捧げた——大義のための個人的損失。今のあなたが選ぼうとしていること、そこには本物の誇りがある。',
    reversed: '自己犠牲の過剰、または正義の暴走。傷ついても正義を守ろうとするのは、あなたがその信念を命がけで信じているから。あなたを大切にすることも、正義の一部。',
  },
  {
    id: 'berkana', name: 'BERKANA', type: 'Rune',
    subs: ['Birch · Birth', 'New Growth'],
    symbol: 'ᛒ', symbolColor: '#bbffaa',
    gradStops: [['#081000','#101e00'], ['#204000','#408800']],
    image: 'images/berkana.png',
    keywords: '白樺・誕生・成長・庇護・母性と再生の力・テュールのアエット',
    upright: '白樺の木、大地の女神。出産、成長、庇護。今、あなたの周りで何か新しいものが芽吹き始めている。今始まろうとしているものを、恐れずに育ててください。',
    reversed: '新しい命への恐れ、または養育の枯渇。まず自分という大地を潤してあげよう。その豊かさの上に、新しい命が育つ。土もまた栄養を必要とする。',
  },
  {
    id: 'ehwaz', name: 'EHWAZ', type: 'Rune',
    subs: ['Horse · Partnership', 'Moving Together'],
    symbol: 'ᛖ', symbolColor: '#ddbb88',
    gradStops: [['#180c00','#302000'], ['#604000','#cc8000']],
    image: 'images/ehwaz.png',
    keywords: '馬・パートナーシップ・移動・信頼と相互尊重・二つが一つになる・テュールのアエット',
    upright: '馬と乗り手のルーン——信頼と相互尊重のパートナーシップ。二つが一つになる時に生まれる速度と優雅さ。あなたが誰かと本当の信頼で繋がっているなら、それは今最も大切にすべきもの。',
    reversed: '信頼への恐れ、または一方的な関係の疲弊。互いを尊重できる関係だけが、本当に遠くへ行ける。馬と乗り手はどちらも等しく大切。',
  },
  {
    id: 'mannaz', name: 'MANNAZ', type: 'Rune',
    subs: ['Human · Self', 'Know Thyself'],
    symbol: 'ᛗ', symbolColor: '#ccbbaa',
    gradStops: [['#101008','#201f10'], ['#3a3828','#706e50']],
    image: 'images/mannaz.png',
    keywords: '人間・自己・知性・自己認識と内省・テュールのアエット',
    upright: '「汝自身を知れ」——内なる知性と社会の中での自分の位置。今のあなたは、自分自身をより深く知る時期にいる。その洞察は周囲の人々にも光をもたらす。',
    reversed: '自己認識の歪み、または他者との境界の喪失。人間であることそのものが、すでに知性の現れ。あなたをあなたとして見る、その目を、まず自分に向けよう。',
  },
  {
    id: 'laguz', name: 'LAGUZ', type: 'Rune',
    subs: ['Water · Flow', 'Trust the Current'],
    symbol: 'ᛚ', symbolColor: '#88ccff',
    gradStops: [['#000c18','#001830'], ['#003366','#0066cc']],
    image: 'images/laguz.png',
    keywords: '水・流れ・直感・無意識の流れ・感情の深み・テュールのアエット',
    upright: '水、湖、海。無意識の流れ、直感、感情の深み。今のあなたの内なる声、感情の深み——それは信頼できる。波のように形を変えながら本質を保つ。',
    reversed: '感情の氾濫、または直感への不信。水は形を変えながら、どこまでも流れ続ける。あなたの直感もまた、止まっていない。その流れに、そっと乗ってみよう。',
  },
  {
    id: 'ingwaz', name: 'INGWAZ', type: 'Rune',
    subs: ['Ing · Potential', 'Inner Completion'],
    symbol: 'ᛜ', symbolColor: '#aaffcc',
    gradStops: [['#001810','#003020'], ['#006650','#00cc99']],
    image: 'images/ingwaz.png',
    keywords: 'イング神・潜在力・完成・種の中に眠る完全な可能性・テュールのアエット',
    upright: '豊穣の神イング（フレイ）のルーン。種の中に眠る完全な可能性——内側に集められたエネルギー。今見えていなくても、あなたの内側では完成に向かうプロセスが進んでいる。',
    reversed: '見えない成果への焦り、または完成を外に出す怖さ。種は暗闇の中でこそ育つ。あなたの内的完成は本物。その準備が整ったとき、あなたは自然に外へと向かえる。',
  },
  {
    id: 'dagaz', name: 'DAGAZ', type: 'Rune',
    subs: ['Dawn · Breakthrough', 'Threshold Moment'],
    symbol: 'ᛞ', symbolColor: '#ffeeaa',
    gradStops: [['#101000','#202000'], ['#404000','#888800']],
    image: 'images/dagaz.png',
    keywords: '夜明け・突破口・変容・意識の覚醒・暗闇が突然光に変わる転換点・テュールのアエット',
    upright: '夜明けの光、昼と夜の境界点。突破口、劇的な変容の瞬間。今、あなたはその閾値の上に立っている。もう少し。その扉の向こうに、あなたが待っていた光がある。',
    reversed: '夜明け前の絶望、または突破口への恐れ。あなたがこれだけ暗闇を歩いてきたことが、光がすぐそこにある証拠。夜明けは来る。その閾値を、一歩だけ、渡ってみよう。',
  },
  {
    id: 'othala', name: 'OTHALA', type: 'Rune',
    subs: ['Homeland · Heritage', 'Return to Root'],
    symbol: 'ᛟ', symbolColor: '#ddbb66',
    gradStops: [['#100c00','#201800'], ['#403000','#887000']],
    image: 'images/othala.png',
    keywords: '故郷・遺産・帰属・先祖の土地・血のつながり・自分が自分であることの根源・テュールのアエット',
    upright: 'フサークの最後のルーン。先祖の土地、受け継がれる遺産。今のあなたは、自分の根っこへと帰る旅の途中にいる。あなたが自分のルーツを大切にするとき、そこから無限の力が湧いてくる。',
    reversed: '帰れない故郷への哀愁、またはルーツからの切断。あなたの中に、すでに故郷がある。あなたが自分自身でいる場所、そこがあなたの故郷。',
  },
];
